// AI Smart Bookmark Organizer 配置文件
// 在 npm run build 之前可以修改此文件

export const CONFIG = {
  // 用户手册地址
  USER_MANUAL_URL: 'https://github.com/SeonPan/ai-smart-bookmark-organizer',
  
  // 预设模型配置
  PRESET_MODELS: [
    { name: 'Kimi', baseUrl: 'https://api.moonshot.cn/v1', model: 'kimi-k2' },
    { name: 'DeepSeek', baseUrl: 'https://api.deepseek.com/v1', model: 'deepseek-chat' },
    { name: 'GLM', baseUrl: 'https://open.bigmodel.cn/api/paas/v4', model: 'GLM-4.6' },
    { name: 'MiniMax', baseUrl: 'https://api.minimax.chat/v1', model: 'MiniMax-M2.1' },
    { name: 'Gemini', baseUrl: 'https://generativelanguage.googleapis.com/v1beta', model: 'gemini-2.5-flash' },
    { name: 'GPT', baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini' },
  ] as const,
  
  // 语言配置
  LANGUAGES: {
    zh: '中文',
    en: 'English'
  } as const,
  
  // 默认语言
  DEFAULT_LANGUAGE: 'zh' as const,
};

// 翻译映射
export const TRANSLATIONS = {
  zh: {
    // 通用
    'app.title': 'AI Smart Bookmark Organizer',
    'app.subtitle': '智能书签管理工具设置',
    'app.loading': '加载中...',
    'app.noData': '暂无数据',
    
    // AI设置
    'ai.title': 'AI 模型配置',
    'ai.description': '选择使用云端 AI 服务或本地 Ollama 模型',
    'ai.cloudApi': '云端 API',
    'ai.localOllama': '本地 Ollama',
    'ai.cloudApiDesc': 'OpenAI / DeepSeek / Moonshot',
    'ai.localOllamaDesc': '无需 API Key，完全本地运行',
    'ai.baseUrl': 'Base URL',
    'ai.apiKey': 'API Key',
    'ai.modelName': 'Model Name',
    'ai.ollamaUrl': 'Ollama 服务地址',
    'ai.ollamaModel': 'Ollama 模型名称',
    'ai.testConnection': '测试连接',
    'ai.quickSelect': '快速选择模型',
    'ai.aiOutputLanguage': 'AI输出语言偏好',
    'ai.cloudConfig': '云端 API 配置',
    'ai.ollamaConfig': 'Ollama 本地配置',
    'ai.apiKeyHint': '您的 API 密钥将安全存储在浏览器中，不会上传到任何服务器',
    'ai.ollamaHint': '请确保 Ollama 服务已在本地启动',
    'ai.testSuccess': '连接成功',
    'ai.testFailed': '连接失败',
    'ai.goSettings': '去设置',
    
    // 整理设置
    'organize.maxCount': '最大整理数量',
    'organize.tokenThreshold': 'Token 预警阈值',
    'organize.tokenDescription': '超过此数量将提示分批处理，避免消耗过多 Token',
    'organize.tokenEstimate': '批处理时消耗的Token预估',
    'organize.basedOn': '基于前 50 个书签的估算',
    'organize.estimatedTokens': '预计 Tokens',
    'organize.estimatedCost': '预计成本',
    
    // 批量整理
    'batch.title': '批量整理',
    'batch.selectBookmarks': '选择要整理的书签',
    'batch.confirmAnalyze': '确认分析',
    'batch.aiProcessing': 'AI 处理',
    'batch.previewResults': '预览结果',
    'batch.selectedCount': '已选择',
    'batch.bookmarks': '个书签',
    'batch.existingFolders': '现有文件夹',
    'batch.startOrganize': '开始整理',
    'batch.processing': 'AI 正在整理...',
    'batch.previewTitle': '整理结果预览',
    'batch.applyChanges': '应用更改',
    'batch.selectAtLeastOne': '请至少选择一个书签',
    'batch.pleaseConfigAI': '请先配置 AI 设置（云端 API 或本地 Ollama）',
    'batch.processingProgress': '处理进度',
    'batch.batchInfo': '正在处理第 {current} / {total} 批书签',
    'batch.snapshotCreated': '已自动创建快照，可随时回滚',
    'batch.analyzed': '已分析',
    'batch.willMove': '将被移动',
    'batch.newFolders': '新建文件夹',
    'batch.willCreateFolders': '将创建以下新文件夹',
    'batch.moreChanges': '还有 {count} 个变更...',
    'batch.organizeComplete': '整理完成！',
    'batch.organizeSuccess': '已成功整理 {count} 个书签',
    'batch.canRollback': '如需撤销，可在「历史记录」中回滚到此快照',
    'batch.continueOrganize': '继续整理',
    
    // 清理大师
    'clean.title': '清理大师',
    'clean.brokenLinks': '失效链接',
    'clean.duplicates': '重复书签',
    'clean.brokenDesc': '扫描并删除无法访问的链接（可能因部分网站的反爬机制导致失效检测有误）',
    'clean.duplicateDesc': '发现并合并重复的书签',
    'clean.noBroken': '未发现失效链接',
    'clean.noDuplicates': '当前无重复书签',
    'clean.scan': '开始扫描',
    'clean.rescan': '重新扫描',
    'clean.deleteSelected': '删除选中',
    'clean.selectKeep': '选择要保留的书签',
    'clean.foundBroken': '发现 {count} 个失效链接',
    'clean.foundDuplicates': '发现 {count} 组重复书签',
    'clean.deleteSuccess': '成功删除 {count} 个',
    
    // 历史记录
    'history.title': '历史记录',
    'history.operationLog': '操作日志',
    'history.snapshots': '历史快照',
    'history.rollback': '回滚',
    'history.delete': '删除',
    'history.confirmRollback': '确认回滚',
    'history.rollbackWarning': '警告：回滚将删除当前所有书签和文件夹，并重建快照中的结构。此操作不可撤销。',
    'history.noLogs': '暂无操作记录',
    'history.noSnapshots': '暂无快照记录',
    'history.affectedCount': '影响 {count} 个书签',
    'history.justNow': '刚刚',
    'history.minutesAgo': '{count} 分钟前',
    'history.hoursAgo': '{count} 小时前',
    'history.daysAgo': '{count} 天前',
    'history.organize': '批量整理',
    'history.clean': '清理大师',
    'history.rollbackOp': '回滚操作',
    'history.other': '其他操作',
    'history.rollbackSuccess': '回滚成功！书签已恢复到选定快照的状态。',
    'history.snapshotTime': '快照时间',
    'history.bookmarkCount': '书签数量',
    'history.description': '描述',
    'history.rollingBack': '回滚中...',
    'history.confirmDelete': '确认删除',
    'history.deleteConfirmMsg': '删除后无法恢复，确定要删除此快照吗？',
    'history.deleting': '删除中...',
    
    // 书签统计
    'stats.title': '书签统计',
    'stats.tabName': '书签统计',
    'stats.totalBookmarks': '书签总数',
    'stats.totalFolders': '文件夹数',
    'stats.maxDepth': '最大深度',
    'stats.refresh': '刷新统计',
    'stats.folderList': '文件夹列表',
    'stats.noFolders': '暂无自定义文件夹',
    'stats.debugInfo': '调试信息',
    'stats.viewRawTree': '查看原始书签树结构',
    
    // 标签可视化
    'tags.title': '标签可视化',
    'tags.description': '按标签下的书签数量展示，气泡越大表示该标签下的书签越多',
    'tags.noTags': '暂无标签数据',
    'tags.useSmartSave': '使用智能保存功能时会自动生成标签',
    'tags.summary': '共 {count} 个智能标签，{bookmarks} 个书签关联',
    'tags.bookmarksCount': '{count} 个书签',
    
    // 关于
    'about.title': '关于 AI Smart Bookmark Organizer',
    'about.tabName': '关于',
    'about.description': 'AI Smart Bookmark Organizer 是一款隐私优先的智能书签管理工具。通过 AI 语义理解技术，帮助您自动整理浏览器收藏夹，解决"只收藏不整理"和"收藏后找不到"的痛点。支持云端 AI 和本地 Ollama 模型，让您的书签管理更智能、更高效。',
    'about.coreFeatures': '核心功能',
    'about.smartSave': '智能保存',
    'about.smartSaveDesc': 'AI 自动分析当前页面内容，智能推荐分类文件夹和标签，一键完成收藏',
    'about.batchOrganize': '批量整理',
    'about.batchOrganizeDesc': '一键整理大量书签，AI 自动归类，支持预览确认和快照回滚',
    'about.cleanMaster': '清理大师',
    'about.cleanMasterDesc': '自动检测失效链接和重复书签，支持选择性删除或合并',
    'about.historyRollback': '历史回滚',
    'about.historyRollbackDesc': '每次整理前自动创建快照，随时回滚到之前的书签状态',
    'about.tagVisualization': '标签可视化',
    'about.tagVisualizationDesc': '以气泡图形式展示标签分布，直观了解书签分类情况',
    'about.privacy': '隐私保护',
    'about.privacyDesc': 'API Key 仅存储在本地，书签数据不上传，支持本地 Ollama 模型',
    'about.userManual': '用户操作手册',
    'about.version': '版本: 1.0.0 | Chrome Extension Manifest V3',
    
    // 智能保存弹窗
    'popup.smartSave': '智能保存',
    'popup.quickSave': '快速保存',
    'popup.edit': '编辑',
    'popup.switchToFullEdit': '切换到完整编辑',
    'popup.title': '标题',
    'popup.url': '网址',
    'popup.aiAnalyze': 'AI 智能分析',
    'popup.reanalyze': '重新分析',
    'popup.analyzing': 'AI 分析中...',
    'popup.saveTo': '保存到',
    'popup.selectFolder': '选择文件夹...',
    'popup.bookmarkBar': '书签栏',
    'popup.myFolders': '我的文件夹',
    'popup.tags': '标签',
    'popup.addTag': '添加标签',
    'popup.add': '添加',
    'popup.cancel': '取消',
    'popup.saveBookmark': '保存书签',
    'popup.saveSuccess': '书签保存成功！',
    'popup.pleaseConfigAI': '请先配置 AI 设置（云端 API 或本地 Ollama）',
    'popup.aiSuggestion': 'AI 建议',
    'popup.confidence': '置信度',
    'popup.reason': '推荐理由',
    'popup.category': '分类',
    'popup.newFolder': '新建文件夹',
    'popup.existingFolder': '现有文件夹',
    'popup.createFolder': '创建文件夹',
    'popup.quickMode': '快速',
    
    // 按钮
    'btn.save': '保存设置',
    'btn.saved': '已保存',
    'btn.cancel': '取消',
    'btn.confirm': '确认',
    'btn.delete': '删除',
    'btn.next': '下一步',
    'btn.back': '返回',
    'btn.close': '关闭',
    'btn.settings': '设置',
  },
  en: {
    // Common
    'app.title': 'AI Smart Bookmark Organizer',
    'app.subtitle': 'Smart Bookmark Manager Settings',
    'app.loading': 'Loading...',
    'app.noData': 'No data',
    
    // AI Settings
    'ai.title': 'AI Model Configuration',
    'ai.description': 'Choose between cloud AI service or local Ollama model',
    'ai.cloudApi': 'Cloud API',
    'ai.localOllama': 'Local Ollama',
    'ai.cloudApiDesc': 'OpenAI / DeepSeek / Moonshot',
    'ai.localOllamaDesc': 'No API Key needed, fully local',
    'ai.baseUrl': 'Base URL',
    'ai.apiKey': 'API Key',
    'ai.modelName': 'Model Name',
    'ai.ollamaUrl': 'Ollama Service URL',
    'ai.ollamaModel': 'Ollama Model Name',
    'ai.testConnection': 'Test Connection',
    'ai.quickSelect': 'Quick Select Model',
    'ai.aiOutputLanguage': 'AI Output Language Preference',
    'ai.cloudConfig': 'Cloud API Configuration',
    'ai.ollamaConfig': 'Ollama Local Configuration',
    'ai.apiKeyHint': 'Your API key will be securely stored in the browser, never uploaded to any server',
    'ai.ollamaHint': 'Please ensure Ollama service is running locally',
    'ai.testSuccess': 'Connection successful',
    'ai.testFailed': 'Connection failed',
    'ai.goSettings': 'Go to Settings',
    
    // Organize Settings
    'organize.maxCount': 'Max Organize Count',
    'organize.tokenThreshold': 'Token Warning Threshold',
    'organize.tokenDescription': 'Will prompt for batch processing if exceeded to avoid excessive Token consumption',
    'organize.tokenEstimate': 'Token Estimate for Batch Processing',
    'organize.basedOn': 'Based on first 50 bookmarks estimate',
    'organize.estimatedTokens': 'Estimated Tokens',
    'organize.estimatedCost': 'Estimated Cost',
    
    // Batch Organize
    'batch.title': 'Batch Organize',
    'batch.selectBookmarks': 'Select Bookmarks to Organize',
    'batch.confirmAnalyze': 'Confirm Analysis',
    'batch.aiProcessing': 'AI Processing',
    'batch.previewResults': 'Preview Results',
    'batch.selectedCount': 'Selected',
    'batch.bookmarks': 'bookmarks',
    'batch.existingFolders': 'Existing Folders',
    'batch.startOrganize': 'Start Organizing',
    'batch.processing': 'AI is organizing...',
    'batch.previewTitle': 'Organize Results Preview',
    'batch.applyChanges': 'Apply Changes',
    'batch.selectAtLeastOne': 'Please select at least one bookmark',
    'batch.pleaseConfigAI': 'Please configure AI settings (Cloud API or Local Ollama)',
    'batch.processingProgress': 'Processing Progress',
    'batch.batchInfo': 'Processing batch {current} / {total}',
    'batch.snapshotCreated': 'Snapshot auto-created, can rollback anytime',
    'batch.analyzed': 'Analyzed',
    'batch.willMove': 'Will be moved',
    'batch.newFolders': 'New folders',
    'batch.willCreateFolders': 'Will create the following new folders',
    'batch.moreChanges': '{count} more changes...',
    'batch.organizeComplete': 'Organize Complete!',
    'batch.organizeSuccess': 'Successfully organized {count} bookmarks',
    'batch.canRollback': 'To undo, rollback to this snapshot in "History"',
    'batch.continueOrganize': 'Continue Organizing',
    
    // Clean Master
    'clean.title': 'Clean Master',
    'clean.brokenLinks': 'Broken Links',
    'clean.duplicates': 'Duplicate Bookmarks',
    'clean.brokenDesc': 'Scan and delete inaccessible links (may be affected by anti-crawling mechanisms)',
    'clean.duplicateDesc': 'Find and merge duplicate bookmarks',
    'clean.noBroken': 'No broken links found',
    'clean.noDuplicates': 'No duplicate bookmarks currently',
    'clean.scan': 'Start Scan',
    'clean.rescan': 'Rescan',
    'clean.deleteSelected': 'Delete Selected',
    'clean.selectKeep': 'Select bookmark to keep',
    'clean.foundBroken': 'Found {count} broken links',
    'clean.foundDuplicates': 'Found {count} duplicate groups',
    'clean.deleteSuccess': 'Successfully deleted {count}',
    
    // History
    'history.title': 'History',
    'history.operationLog': 'Operation Log',
    'history.snapshots': 'History Snapshots',
    'history.rollback': 'Rollback',
    'history.delete': 'Delete',
    'history.confirmRollback': 'Confirm Rollback',
    'history.rollbackWarning': 'Warning: Rollback will delete all current bookmarks and folders, and rebuild from snapshot. This cannot be undone.',
    'history.noLogs': 'No operation records',
    'history.noSnapshots': 'No snapshots yet',
    'history.affectedCount': 'Affected {count} bookmarks',
    'history.justNow': 'Just now',
    'history.minutesAgo': '{count} minutes ago',
    'history.hoursAgo': '{count} hours ago',
    'history.daysAgo': '{count} days ago',
    'history.organize': 'Batch Organize',
    'history.clean': 'Clean Master',
    'history.rollbackOp': 'Rollback',
    'history.other': 'Other',
    'history.rollbackSuccess': 'Rollback successful! Bookmarks restored to selected snapshot state.',
    'history.snapshotTime': 'Snapshot Time',
    'history.bookmarkCount': 'Bookmark Count',
    'history.description': 'Description',
    'history.rollingBack': 'Rolling back...',
    'history.confirmDelete': 'Confirm Delete',
    'history.deleteConfirmMsg': 'Cannot be recovered after deletion. Are you sure?',
    'history.deleting': 'Deleting...',
    
    // Stats
    'stats.title': 'Bookmark Statistics',
    'stats.tabName': 'Stats',
    'stats.totalBookmarks': 'Total Bookmarks',
    'stats.totalFolders': 'Total Folders',
    'stats.maxDepth': 'Max Depth',
    'stats.refresh': 'Refresh Statistics',
    'stats.folderList': 'Folder List',
    'stats.noFolders': 'No custom folders yet',
    'stats.debugInfo': 'Debug Info',
    'stats.viewRawTree': 'View raw bookmark tree structure',
    
    // Tags
    'tags.title': 'Tag Visualization',
    'tags.description': 'Display by bookmark count per tag, larger bubbles indicate more bookmarks',
    'tags.noTags': 'No tag data yet',
    'tags.useSmartSave': 'Tags are automatically generated when using Smart Save',
    'tags.summary': '{count} smart tags, {bookmarks} bookmarks associated',
    'tags.bookmarksCount': '{count} bookmarks',
    
    // About
    'about.title': 'About AI Smart Bookmark Organizer',
    'about.tabName': 'About',
    'about.description': 'AI Smart Bookmark Organizer is a privacy-first smart bookmark management tool. Using AI semantic understanding technology, it helps you automatically organize browser bookmarks, solving the pain points of "only collecting without organizing" and "can\'t find after collecting". Supports cloud AI and local Ollama models for smarter, more efficient bookmark management.',
    'about.coreFeatures': 'Core Features',
    'about.smartSave': 'Smart Save',
    'about.smartSaveDesc': 'AI automatically analyzes page content, recommends folders and tags, one-click collection',
    'about.batchOrganize': 'Batch Organize',
    'about.batchOrganizeDesc': 'One-click organize large numbers of bookmarks, AI auto-categorization with preview and rollback',
    'about.cleanMaster': 'Clean Master',
    'about.cleanMasterDesc': 'Auto-detect broken links and duplicates, support selective deletion or merging',
    'about.historyRollback': 'History Rollback',
    'about.historyRollbackDesc': 'Auto-create snapshots before each organize, rollback to previous state anytime',
    'about.tagVisualization': 'Tag Visualization',
    'about.tagVisualizationDesc': 'Display tag distribution as bubble chart, intuitively understand bookmark categories',
    'about.privacy': 'Privacy Protection',
    'about.privacyDesc': 'API Key stored locally only, bookmark data not uploaded, supports local Ollama model',
    'about.userManual': 'User Manual',
    'about.version': 'Version: 1.0.0 | Chrome Extension Manifest V3',
    
    // Popup
    'popup.smartSave': 'Smart Save',
    'popup.quickSave': 'Quick Save',
    'popup.edit': 'Edit',
    'popup.switchToFullEdit': 'Switch to Full Edit',
    'popup.title': 'Title',
    'popup.url': 'URL',
    'popup.aiAnalyze': 'AI Smart Analyze',
    'popup.reanalyze': 'Re-analyze',
    'popup.analyzing': 'AI analyzing...',
    'popup.saveTo': 'Save to',
    'popup.selectFolder': 'Select folder...',
    'popup.bookmarkBar': 'Bookmarks Bar',
    'popup.myFolders': 'My Folders',
    'popup.tags': 'Tags',
    'popup.addTag': 'Add tag',
    'popup.add': 'Add',
    'popup.cancel': 'Cancel',
    'popup.saveBookmark': 'Save Bookmark',
    'popup.saveSuccess': 'Bookmark saved successfully!',
    'popup.pleaseConfigAI': 'Please configure AI settings (Cloud API or Local Ollama)',
    'popup.aiSuggestion': 'AI Suggestion',
    'popup.confidence': 'confidence',
    'popup.reason': 'Reason',
    'popup.category': 'Category',
    'popup.newFolder': 'New Folder',
    'popup.existingFolder': 'Existing Folder',
    'popup.createFolder': 'Create Folder',
    'popup.quickMode': 'Quick',
    
    // Buttons
    'btn.save': 'Save Settings',
    'btn.saved': 'Saved',
    'btn.cancel': 'Cancel',
    'btn.confirm': 'Confirm',
    'btn.delete': 'Delete',
    'btn.next': 'Next',
    'btn.back': 'Back',
    'btn.close': 'Close',
    'btn.settings': 'Settings',
  }
} as const;

export type TranslationKey = keyof typeof TRANSLATIONS.zh;
export type Language = 'zh' | 'en';
